### ISSUE TITLE
fusionath-app 1.37.0 won't start

### ISSUE THREAD

**Issue by oottinger** [FusionAuth/homebrew-fusionauth#8]
I just upgraded to 1.37.0, and when trying to start `fusionauth-app` I get an error.  The logs show the catalina is missing:

```
sh: catalina.sh: No such file or directory
```

I tried uninstalling, and reinstalling in case the upgrade failed and a fresh install did not work for me either.  For now I switched to the previous install.

**Comment by robotdan** [comment]
fixed via https://github.com/FusionAuth/homebrew-fusionauth/commit/67ad6635fb2e8d7ae70b7b38083299fec02c012f
I re-pushed the `1.37.0` tag for this repo, let me know if that fixes you up.

**Comment by oottinger** [comment]
It's fixed, thanks!
